### PR TITLE
Adding support for a separator

### PR DESCRIPTION
**Pull request by sramam**
`'_____':''` - that's 5 '_', is treated as a separator.

### CODE REVIEW

**Comment by ewnd9** [comment]
Thanks for the effort but it looks like it could be achieved like this without the new code

``` js
var inquirer = require('inquirer-question');

inquirer
  .prompt({
    type: 'list',
    message: 'hi',
    choices: {
      'test-1': function() {
        // some computatations
        return 1;
      },
      'test-2': 2,
      [new inquirer.Separator()]: undefined
    }
  })
  .then(function(result) {
    console.log(result); //=> 1 or 2
  });
```

or in pre 4.0 node

```
var inquirer = require('inquirer-question');
var choices = {
  'test-1': function() {
    // some computatations
    return 1;
  },
  'test-2': 2,
};

choices[new inquirer.Separator()] = undefined;

inquirer
  .prompt({
    type: 'list',
    message: 'hi',
    choices: choices 
  }).then(function(result) {
    console.log(result); //=> 1 or 2
  });
```

Also, please watch https://egghead.io/lessons/javascript-how-to-squash-multiple-git-commits about squashing commits (right now your pull requests contain 3 commits, should be one)

**Comment by sramam** [comment]
I have a complicated menu structure, some with dynamic choices and some
with static choices.
With the pull request, I can represent each page like below. Which I think
is syntactically concise,
pleasant to look at and understand. Hence the effort.

I'll leave the decision to accept the PR to you.

Thanks for the library. It simplified our code structure substantially.

// static
  return inquirer.prompt({
    type: 'list',
    name: 'context',
    message: 'Make a choice',
    choices: {
      'Vanilla': 'vanilla',
      'Chocolate': 'chocolate',
      'Strawberry': 'strawberry',
      _____: '',
      'I want cake': 'cake',
      "[exit] I'm on a diet ": 'exit'
    }
  }).then(function A(result) {
    return { next: result };
  });

// dynamic
  var flavors = [some array].reduce(function(acc, flv) {
    var f = {}
    f[flv] = flv;
    return extend(acc, f);
  }
  return inquirer.prompt({
    type: 'list',
    name: 'context',
    message: 'Make a choice',
    choices: extend(
      flavors,
      {
      _____: '',
      'I want cake': 'cake',
      "[exit] I'm on a diet ": 'exit'
      }
    )
  }).then(function A(result) {
    return { next: result };
  });

On Thu, Mar 10, 2016 at 6:16 AM, ewnd9 notifications@github.com wrote:

> Thanks for the effort but it looks like it could be achieved like this
> without the new code
> 
> var inquirer = require('inquirer-question');
> 
> inquirer
>   .prompt({
>     type: 'list',
>     message: 'hi',
>     choices: {
>       'test-1': function() {
>         // some computatations
>         return 1;
>       },
>       'test-2': 2,
>       [new inquirer.Separator()]: undefined
>     }
>   })
>   .then(function(result) {
>     console.log(result); //=> 1 or 2
>   });
> 
> or in pre 4.0 node
> 
> var inquirer = require('inquirer-question');
> var choices = {
>   'test-1': function() {
>     // some computatations
>     return 1;
>   },
>   'test-2': 2,
> };
> 
> choices[new inquirer.Separator()] = undefined;
> 
> inquirer
>   .prompt({
>     type: 'list',
>     message: 'hi',
>     choices: choices
>   }).then(function(result) {
>     console.log(result); //=> 1 or 2
>   });
> 
> Also, please watch
> https://egghead.io/lessons/javascript-how-to-squash-multiple-git-commits
> about squashing commits (right now your pull requests contain 3 commits,
> should be one)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ewnd9/inquirer-question/pull/1#issuecomment-194865902
> .

## 

Imagine there were no hypothetical situations. ಠ_ಠ

**Comment by ewnd9** [comment]
I've just cherry-picked one of your commits https://github.com/ewnd9/inquirer-question/commit/4f420f42dd5b1305256259884ede3df523508477, now pull request is kind of merged.

New version `v1.2.0` with your changes is available now on npm.

---

But seriously, take a look at video lesson from my previous comment about squashing. Most of the users on github wouldn't accept pull request containing overlapping commits for simple changes (your original pr contain 3 commits, second overwriting changes of the first one and the third is simple empty)

**Comment by ewnd9** [comment]
Also, you may want to add email from the commit to your github settings so the commit can be associated with your profile

**Comment by sramam** [comment]
Perfect.
Now I don't have to maintain an npm install from a git url.
And thanks for picking only the cherry!  :)

-shishir

On Thu, Mar 10, 2016 at 7:06 AM, ewnd9 notifications@github.com wrote:

> Also, you may want to add email from the commit to your github settings so
> the commit can be associated with your profile
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ewnd9/inquirer-question/pull/1#issuecomment-194891539
> .

## 

Imagine there were no hypothetical situations. ಠ_ಠ

**Pull request closed without merging**
